name: Dependency Review

on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - master
      - release/**


permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
      - name: Dependency Review
        uses: actions/dependency-review-action@v4

