name: Publish Artifacts and Release Documentation

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'
  JF_URL: 'http://localhost:8081'
  OIDC_PROVIDER: 'github'
  OIDC_AUDIENCE: 'github-workflows'

jobs:
#  ci:
#    uses: ./.github/workflows/ci.yml
#
#  ci-low-cadence:
#    uses: ./.github/workflows/ci-low-cadence.yml
#
#  codeql:
#    uses: ./.github/workflows/codeql.yml

  release-java:
    name: Release java artifacts
    permissions:
      contents: read
      packages: write
#    needs: [ ci, ci-low-cadence, codeql]
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ossrhPassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
#      - name: Build with Gradle
#        run: ./gradlew tutorialPublish -Paeron.ci.apiKey=${{ secrets.WIKI_PAGE_TOKEN }} --stacktrace

  release-c:
    name: Release c artifacts
    permissions:
      contents: read
      id-token: write
      packages: write
#    needs: [ ci, ci-low-cadence, codeql]
    runs-on: [ self-hosted ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu
            version: 20.04
          - distro: ubuntu
            version: 22.04
          - distro: debian
            version: bullseye
          - distro: debian
            version: bookworm
          - distro: rocky
            version: 8.9
          - distro: awslinux
            version: 2023
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Get aeron version
        run: echo "aeron_version=$(cat version.txt)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Artifacts Using Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cppbuild/${{ matrix.distro }}/Dockerfile
          pull: true
          shm-size: 1g
          outputs: build/${{ matrix.distro }}/${{ matrix.version }}
          target: essentials-artifacts
          build-args: VERSION=${{ matrix.version }}
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}
          oidc-audience: ${{ env.OIDC_AUDIENCE }}
      - name: Publish Build info With JFrog CLI
        run: |
          mv *.tar.gz aeron-${{ env.aeron_version }}-${{ matrix.distro }}-${{ matrix.version }}.tar.gz
          jf rt u *.tar.gz 'generic-local/'
        working-directory: ./build/${{ matrix.distro }}/${{ matrix.version }}