name: Publish Artifacts and Release Documentation

on:
  workflow_dispatch:
    inputs:
      release:
        description: Is release? (Will create tag and update version)
        required: true
        default: false
        type: boolean
      release-version:
        description: Released version (x.y.z)
        required: true
        type: string
      next-version:
        description: Next version (x.y.z)
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false -Dorg.gradle.warning.mode=fail'
  AERON_REPO_PATH: 'generic-local/'
  AERON_REPO_TEST_PATH: 'generic-local/'

jobs:
#  ci:
#    uses: ./.github/workflows/ci.yml
#
#  ci-low-cadence:
#    uses: ./.github/workflows/ci-low-cadence.yml
#
#  codeql:
#    uses: ./.github/workflows/codeql.yml

  pre-release:
    name: Update version, tag repo, and return sha
    permissions:
      contents: write
#    needs: [ ci, ci-low-cadence, codeql ]
    runs-on: self-hosted
    outputs:
      sha: ${{ steps.return-details.outputs.sha }}
      version: ${{ steps.return-details.outputs.version }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - id: validate
        name: Validate no new commits
        run: |
          current_sha=$(git rev-parse HEAD)
          if test $current_sha != '${{ github.sha }}'
          then exit 1
          fi
      - id: tag-version
        if: ${{ inputs.release }}
        name: Update version and tag repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@aeron.io"
          echo ${{ inputs.release-version }} > version.txt
          git add version.txt
          git status
          git commit -m "${{ inputs.release-version }} version update."
          git push
          git tag ${{ inputs.release-version }}
          git push origin refs/tags/${{ inputs.release-version }}
      - id: return-details
        name: Return current SHA and version
        run: |
          echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
          
          if test ${{ inputs.release }} 
          then echo "sha=${{ inputs.release-version }}" >> "$GITHUB_OUTPUT"
          else echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          fi
          
  github-release:
    name: Create Github Release
    permissions:
      contents: write
    needs: pre-release
    runs-on: self-hosted
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.pre-release.outputs.sha }}
      - id: create-release
        name: Create Release
        if: ${{ inputs.release }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.pre-release.outputs.sha }}
          release_name: Release ${{ needs.pre-release.outputs.sha }}
          draft: true

  release-java:
    name: Release java artifacts
    permissions:
      contents: read
      packages: write
    needs: github-release
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.pre-release.outputs.sha }}
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Setup BUILD_JAVA_HOME & BUILD_JAVA_VERSION
        run: |
          java -Xinternalversion
          echo "BUILD_JAVA_HOME=${JAVA_HOME}" >> $GITHUB_ENV
          echo "BUILD_JAVA_VERSION=8" >> $GITHUB_ENV
      - name: Publish with Gradle
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.ossrhUsername }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.ossrhPassword }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signingPassword }}
#      - name: Build with Gradle
#        run: ./gradlew tutorialPublish -Paeron.ci.apiKey=${{ secrets.WIKI_PAGE_TOKEN }} --stacktrace

  release-c:
    name: Release c artifacts
    permissions:
      contents: write
      id-token: write
      packages: write
    needs: github-release
    runs-on: [ self-hosted ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu
            version: 20.04
#          - distro: ubuntu
#            version: 22.04
#          - distro: debian
#            version: bullseye
#          - distro: debian
#            version: bookworm
#          - distro: rocky
#            version: 8.9
#          - distro: awslinux
#            version: 2023
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.pre-release.outputs.sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Artifacts Using Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cppbuild/${{ matrix.distro }}/Dockerfile
          pull: true
          shm-size: 1g
          outputs: build
          target: essentials-artifacts
          build-args: VERSION=${{ matrix.version }}
      - name: Rename artifact
        run: |
          artifact_name=aeron-${{ needs.pre-release.outputs.version }}-${{ matrix.distro }}-${{ matrix.version }}.tar.gz
          echo "artifact_name=$artifact_name" >> $GITHUB_ENV
          mv *.tar.gz $artifact_name
        working-directory: ./build
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: 'http://localhost:8081'
        with:
          oidc-provider-name: 'github'
          oidc-audience: 'github-workflows'
      - name: Publish Build info With JFrog CLI
        run: jf rt u *.tar.gz ${{ env.AERON_REPO_PATH }}
        working-directory: ./build
      - name: Upload to Github Release
        if: ${{ inputs.release }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.github-release.outputs.upload_url }}
          asset_path: ./build/${{ env.artifact_name }}
          asset_name: ${{ env.artifact_name }}
          asset_content_type: application/gzip

  post-release:
    name: Update version
    permissions:
      contents: write
    needs: [ release-java, release-c ]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Commit snapshot version to current branch
        if: ${{ inputs.release }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@aeron.io"
          echo ${{ inputs.next-version }}-SNAPSHOT > version.txt
          git add version.txt
          git status
          git commit -m "${{ inputs.next-version }}-SNAPSHOT version update."
          git push
